apiVersion: 1

datasources:
  - name: HireHub Metrics API
    type: yesoreyeram-infinity-datasource
    access: proxy
    url: http://api:8000
    isDefault: true
    jsonData:
      url_options:
        method: GET
      headers:
        - name: Content-Type
          value: application/json
